/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:65d4c399-8e89-4ebf-ab15-4bec85e83b36",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_uMHGsJrMl",
    "aws_user_pools_web_client_id": "hosn6k7q462fjm2rftq67die6",
    "oauth": {}
};


export default awsmobile;
